
import type { Metadata } from "next";
import React from "react";
import  Provider  from "./provider";
import { Container } from "@chakra-ui/react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header/>
          <Container>
            {children}
          </Container>
          <Footer/>
        </Provider>


      </body>
    </html>
  );
}
