import type { Metadata } from "next";
import React from "react";
import { Provider } from "@/components/ui/provider";
import { Box, Container } from "@chakra-ui/react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Provider>
          <Box bg={{ base: "white", _dark: "black" }} minH="100vh">
            <Header />
            <Container>{children}</Container>
            <Footer />
          </Box>
        </Provider>
      </body>
    </html>
  );
}
